spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: '0000'
mybatis:
  mapper-locations: classpath:mapper/*.xml